# Servidor
server.port=8080

# Banco de dados
spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
spring.datasource.driver-class-name=org.postgresql.Driver
SPRING_DATASOURCE_USERNAME=postgres
SPRING_DATASOURCE_PASSWORD=cRxhBWitGpPzClpNbFZQYbZUJmQlBDOs

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
SPRING_JPA_HIBERNATE_DDL_AUTO=none

upload.dir=uploads/imagens

# JWT
jwt.secret=sua_chave_secreta_bem_longa_aqui_minimo_256bits
jwt.expiration=86400000